[package]
name = "not-grocy-server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
diesel = { version = "1.4", features = ["sqlite", "postgres", "chrono", "r2d2"] }
dotenv = "0.15"
chrono = { version = "0.4", features = ["serde"] }
r2d2 = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
barrel = "0.6"