kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.22.0
controlPlaneEndpoint: "kube-apiserver.selfmade4u.de:6443"
networking:
  podSubnet: "10.244.0.0/16"
#featureGates:
#  RootlessControlPlane: true
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
#featureGates:
#  MemoryQoS: true